export { ramDynamicReducer, ramStaticReducer ,ramDynamicAction, ramStaticAction } from './ram'
export { gpuDynamicReducer, gpuStaticReducer, gpuDynamicAction, gpuStaticAction } from './gpu'
export { cpuDynamicReducer, cpuStaticReducer, cpuDynamicAction, cpuStaticAction } from './cpu'
export { hdDynamicReducer, hdStaticReducer, hdDynamicAction, hdStaticAction } from './hd'
export { dynamicDataReducer, staticDataReducer } from './storeData'
export { supportReducer, supportAction } from 'shared/store/support' 

export { DynamicData, StaticData } from './storeData'
export { GpuDynamic, GpuStatic  } from './gpu/index' 
export { CpuDynamic, CpuStatic } from './cpu/index' 
export { RamDynamic, RamStatic } from './ram/index' 
export { HdDynamic, HdStatic  } from './hd/index'
export { Support } from 'shared/store/support/index' 